### PR TITLE
Fix Typescript Models and Tests

### PR DESCRIPTION
**Pull request by schwarmco**
Related to 
- https://github.com/manticoresoftware/manticoresearch-typescript/pull/2
- https://github.com/manticoresoftware/manticoresearch-typescript/issues/3

The Typescript Package is not working for me, because aggregations and expressions are wrongly typed - with this PR i want to a) proof this with failing test cases b) fix the typings that i am aware of and c) improve the overall typescript package

### CODE REVIEW

**Comment by schwarmco** [comment]
Currently tests are failing but marked as green:

```shell
$ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

✔  Utils Api Tests
ResponseError: Response returned an error code
    at UtilsApi.request (~/src/github.com/schwarmco/manticoresearch-openapi/out/manticoresearch-typescript/src/runtime.ts:135:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UtilsApi.sqlRaw (~/src/github.com/schwarmco/manticoresearch-openapi/out/manticoresearch-typescript/src/apis/UtilsApi.ts:45:26)
    at async UtilsApi.sql (~/src/github.com/schwarmco/manticoresearch-openapi/out/manticoresearch-typescript/src/apis/UtilsApi.ts:61:26)
    at async Context.<anonymous> (~/src/github.com/schwarmco/manticoresearch-openapi/out/manticoresearch-typescript/test/manual.test.ts:21:13) {
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 501,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Implemented',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

in the next commit i will make the tests fail on error responses

**Comment by schwarmco** [comment]
Tests are now failing correctly:

```shell
$ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
Error response: {
  "error": "only SELECT queries are supported"
}
    1) Testing utils api operations

  Index API Tests
Error response: {
  "error": "only SELECT queries are supported"
}
    2) Testing index api operations

  Search Api Tests
Error response: {
  "error": "only SELECT queries are supported"
}
    3) Testing search api operations


  0 passing (38ms)
  3 failing

  1) Utils Api Tests
       Testing utils api operations:
     AssertionError: expected ResponseError: Response returned an error… { response: Response{ …(3) } } to be null
      at Context.<anonymous> (test/manual.test.ts:35:22)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) Index API Tests
       Testing index api operations:
     AssertionError: expected ResponseError: Response returned an error… { response: Response{ …(3) } } to be null
      at Context.<anonymous> (test/manual.test.ts:148:22)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  3) Search Api Tests
       Testing search api operations:
     AssertionError: expected ResponseError: Response returned an error… { response: Response{ …(3) } } to be null
      at Context.<anonymous> (test/manual.test.ts:231:22)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by schwarmco** [comment]
Looking at the other clients:

- https://github.com/manticoresoftware/openapi/blob/c9296488892734049fc4a2dd508eb8987876ed96/out/manticoresearch-python/test/test_manual.py#L33
- https://github.com/manticoresoftware/openapi/blob/c9296488892734049fc4a2dd508eb8987876ed96/out/manticoresearch-elixir/test/api_index_test.exs#L31

`utilsApi.sql` generally does not require the `rawResponse` parameter to be defined to allow queries like `TRUNCATE` or `SHOW TABLES` - therefore i defaulted the flag to `true`. Are you fine with this @Nick-S-2018 @sanikolaev ?

with the last commit (b0e54d2), the tests are green:

```shell

$ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
    ✔ Testing utils api operations

  Index API Tests
    ✔ Testing index api operations

  Search Api Tests
    ✔ Testing search api operations


  3 passing (58ms)
```

**Comment by schwarmco** [comment]
Adding a Test Case with an Aggregation Array according to the Typescript Typings and the OpenAPI spec found here:

https://github.com/manticoresoftware/openapi/blob/c9296488892734049fc4a2dd508eb8987876ed96/out/manticoresearch-typescript/src/models/index.ts#L895

https://github.com/manticoresoftware/openapi/blob/master/manticore.yml#L625-L628

This results in a failed test result with the manticoresearch-server responding `aggs property should be an object`:

```shell
 $ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
    ✔ Testing utils api operations

  Index API Tests
    ✔ Testing index api operations

  Search Api Tests
    ✔ Testing search api operations
Error response: {
  "name": "AssertionError",
  "message": "expected [ { total: +0, warning: '', …(1) } ] to have deep nested property 'hits.total'",
  "showDiff": false,
  "actual": [
    {
      "total": 0,
      "warning": "",
      "error": "\"aggs\" property should be an object\""
    }
  ]
}
    1) Testing search aggregation


  3 passing (78ms)
  1 failing

  1) Search Api Tests
       Testing search aggregation:
     AssertionError: expected AssertionError{ …(5) } to be null
      at Context.<anonymous> (test/manual.test.ts:254:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by schwarmco** [comment]
Warning: The last commit 9261364 breaks all clients (the need to be rebuilt) because it changes the OpenAPI Spec - but it basically makes aggregations work:

https://github.com/schwarmco/manticoresearch-openapi/blob/feature/typescript-tests/out/manticoresearch-typescript/test/manual.test.ts#L236-L253

Resulting in all green tests:

```shell
$ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
    ✔ Testing utils api operations

  Index API Tests
    ✔ Testing index api operations

  Search Api Tests
    ✔ Testing search api operations
    ✔ Testing search aggregation

  4 passing (76ms)
```

@sanikolaev have you had a chance to review the OpenAPI spec with the team?

**Comment by sanikolaev** [comment]
Thank you for the PR, @schwarmco !

> @sanikolaev have you had a chance to review the OpenAPI spec with the team?

Yes, we confirmed what you found is a mistake in it. Sorry we've been busy with other things lately, but are now getting back to the client issues. 

@Nick-S-2018 pls review this PR.

**Review by Nick-S-2018 — CHANGES_REQUESTED** [review]
@schwarmco, thank you for your contribution, the PR is great!  There's just one thing to do: can you please remove all changes in the `out` folder from it? The point is that we generate the clients manually and then apply ci to push generated code to the respective repos and publish it to public registries automatically, so we don't need to update the client directly here.

**Comment by schwarmco** [comment]
@Nick-S-2018 thank you for the feedback! happy to hear that this works for you! if you wouldn't mind, i'd do the same thing for the `expressions` (adding failing tests, fix openapi spec and add working tests) before finalizing this PR. Of course i can remove the changes in `out`

**Comment by schwarmco** [comment]
so... according to the current openapi spec, `expressions` is an array - but the test fails:

```shell
npm run test             

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
    ✔ Testing utils api operations (43ms)

  Index API Tests
    ✔ Testing index api operations

  Search Api Tests
    ✔ Testing search api operations
    ✔ Testing search aggregation
Error response: {
  "name": "AssertionError",
  "message": "expected [ { total: +0, warning: '', …(1) } ] to ...",
  "showDiff": false,
  "actual": [
    {
      "total": 0,
      "warning": "",
      "error": "\"expressions\" property should be an object"
    }
  ]
}
```

**Comment by schwarmco** [comment]
With the updated OpenAPI Spec ([according to the docs](https://manual.manticoresearch.com/Searching/Expressions#expressions)) adding expressions to a search is working:

https://github.com/manticoresoftware/openapi/blob/57c1dd68fc170b7b78e4d4b328307db4e7754f19/test/typescript/manual.test.ts#L262-L275

```shell
$ npm run test

> manticoresearch-ts@3.3.1 test
> cross-env TS_NODE_COMPILER_OPTIONS='{"module": "commonjs" }' mocha -r ts-node/register 'test/**/*.test.ts'

  Utils Api Tests
    ✔ Testing utils api operations

  Index API Tests
    ✔ Testing index api operations

  Search Api Tests
    ✔ Testing search api operations
    ✔ Testing search aggregation
    ✔ Testing search expressions

  5 passing (85ms)
```

**Review by Nick-S-2018 — APPROVED** [review]
Yes, expressions work fine in tests now.

**Pull request merged**
