### PR TITLE
dotnet HTTP API client

### PR DESCRIPTION
**Pull request by mihaj**

### CODE REVIEW

**Comment by mihaj** [comment]
> Hi mihay, You've committed only the code of the generated client itself, but we also need all the source templates from the OpenApi which have been used to generate it. Can you please provide them too?

Hey, I've run the container version:

```powershell
docker run --rm -v <local_folder>:/local openapitools/openapi-generator-cli generate -i /local/manticore.yml -g csharp-netcore --library httpclient --additional-properties=targetFramework=netstandard2.1 --additional-properties=packageName=ManticoreSearch -o /local/out/csharp
```
Can you point me in the right direction, on how I can generate this config file?

**Comment by Nick-S-2018** [comment]
Hi ,
If you didn't add any changes to the default openapi-generator templates you can just take them from [here](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/csharp-netcore), replace the necessary ones with their corresponding versions from [here](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient) (as you used this library), and, finally, create `templates/net` folder and place them into it.

Another thing that should be dealt with is testing. Auto tests generated by the Openapi don't cover the functionality of clients so it's necessary to add most important tests (covering the indexApi and searchApi usage) manually before we can add a client to the project. See, for example, how it's done for the [Python client](https://github.com/manticoresoftware/openapi/tree/master/test/python). It would be great if you reproduce the api tests from there for the .net client. 
Also, take note that we run all the client tests via CI/CD in a prepared environment but you'll need to create necessary indexes by hand to check your tests. For this, use the following sql requests:
```
CREATE TABLE test(content text, name text attribute, cat integer);
CREATE TABLE test_pq(content text, name text attribute, cat integer) type='pq';
```
Then you can run your tests safely. After the tests are ready and checked, just create `test/net `folder and place them into it.

**Comment by sanikolaev** [comment]
@mihaj any news on this?

**Comment by mihaj** [comment]
@Nick-S-2018 I've created the `templates/net` folder, can you give me the CLI command to generate the HTTP client from the templates above?

**Comment by Nick-S-2018** [comment]
Hi,
I'm sorry for being late with the response.
Just add the template folder path to the command you've previously used:

```powershell
docker run --rm -v <local_folder>:/local openapitools/openapi-generator-cli generate -t /local/templates/net -i /local/manticore.yml -g csharp-netcore --library httpclient --additional-properties=targetFramework=netstandard2.1 --additional-properties=packageName=ManticoreSearch -o /local/out/csharp
```

**Comment by Nick-S-2018** [comment]
We've finally generated the .Net client version with the OpenAPI Generator and published it [here](https://github.com/manticoresoftware/manticoresearch-net/)

**Pull request closed without merging**
